---
- name: to install yum module
  hosts: web02
  become: true
  vars_files:
   - variable-file
  tasks:
  - name: check and install "{{ web_pkg }}" and "{{ firewall_pkg }}"
    yum:
     name:
      - "{{ web_pkg }}"
      - "{{ firewall_pkg }}"
      - "{{ python_pkg }}"
     state: latest

