---
- name: to install yum module
  hosts: web02
  become: true
  vars_files:
   - variable-file
  tasks:
  - name: check and install "{{ web_pkg }}" and "{{ firewall_pkg }}"
    yum:
     name:
      - "{{ web_pkg }}"
      - "{{ firewall_pkg }}"
      - "{{ python_pkg }}"
     state: latest
  
  - name: loop with service started and enabled
    service:
     name: "{{ item }}"
     state: started
     enabled: yes
    loop:
     - "{{ web_pkg }}"
     - "{{ firewall_pkg }}"
  - name: http web content 
    copy:
     content: Web02 server hosted on httpd 
     dest: "{{ web_content }}"

  - name: open "{{ http }}" service on "{{ firewall_pkg }}"
    firewalld:
     service: "{{ http }}"
     permanent: yes
     immediate: yes
     state: enabled
     
